Debugging model filepaths keys

diff --git a/.github/workflows/ci-tests.yaml b/.github/workflows/ci-tests.yaml
--- a/.github/workflows/ci-tests.yaml
+++ b/.github/workflows/ci-tests.yaml
@@ -36,15 +36,16 @@ jobs:
 
       - name: Run tests and coverage
         run: |
-          poetry run coverage run --source=fhibe_eval_api/ -m pytest -s tests 
-          poetry run coverage report
-          poetry run coverage xml -o coverage.xml
-          COVERAGE_THRESHOLD=70
-          coverage_percentage=$(poetry run coverage report | awk '/^TOTAL/ { print $NF }' | tr -d '%')
-          if [ "$coverage_percentage" -lt "$COVERAGE_THRESHOLD" ]; then
-            echo "Fail: Coverage threshold ($COVERAGE_THRESHOLD%) not met. Coverage percentage: $coverage_percentage%"
-            exit 1
-          else
-            echo "Success: Coverage threshold ($COVERAGE_THRESHOLD%) met. Coverage percentage: $coverage_percentage%"
-          fi
+          poetry run pytest -s tests/test_percentage_correct_keypoints
+          # poetry run coverage run --source=fhibe_eval_api/ -m pytest -s tests 
+          # poetry run coverage report
+          # poetry run coverage xml -o coverage.xml
+          # COVERAGE_THRESHOLD=70
+          # coverage_percentage=$(poetry run coverage report | awk '/^TOTAL/ { print $NF }' | tr -d '%')
+          # if [ "$coverage_percentage" -lt "$COVERAGE_THRESHOLD" ]; then
+          #   echo "Fail: Coverage threshold ($COVERAGE_THRESHOLD%) not met. Coverage percentage: $coverage_percentage%"
+          #   exit 1
+          # else
+          #   echo "Success: Coverage threshold ($COVERAGE_THRESHOLD%) met. Coverage percentage: $coverage_percentage%"
+          # fi
         shell: bash
